services:
  discord-bot:
    build: .
    container_name: discord_bot
    working_dir: /app
    command: python bot.py
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OWNER_USERNAME: ${OWNER_USERNAME}
      LOG_CHANNEL_NAME: ${LOG_CHANNEL_NAME}
      SERVER_ID: ${SERVER_ID}
    restart: unless-stopped